### ISSUE TITLE
Design login screen & Sign up Screen

### ISSUE THREAD

**Issue by moniruzzaman76** [moniruzzaman76/Snap-Share#1]
![Screen-2 1-1](https://github.com/moniruzzaman76/Snap-Share/assets/98202630/87a967a6-62ea-4f67-adca-64c61d93fddc)
![Screen-2 1](https://github.com/moniruzzaman76/Snap-Share/assets/98202630/a5825089-b614-464f-a51f-6b5a59f8902f)
please follow figma design

**Comment by saymanrifat** [comment]
Vai Kivabe korbo
